### ISSUE TITLE
Many Lo-Fi spellings - are they all intended?

### ISSUE THREAD

**Issue by jsirois** [karlstolley/lo-fi#1]
The stats:

```
git grep -i -E "lofi|lo-fi" -- stolley/index.html | sed -r -e "s|.*([Ll][Oo]-?[Ff][Ii]).*|\1|g" | sort | uniq -c | sort -nr
     37 lo-fi
      8 Lo-fi
      6 Lo-Fi
      2 LOFI
      1 lofi
```

The 1 `lofi` is part of markup and the `lo-fi` and `LOFI` appear to be used consistently in obvious ways.  I was wondering about the (non-markup) instances of `Lo-Fi` vs `Lo-fi` though.   It looks like `Lo-Fi` is reserved for headings and `Lo-fi` for the 1st word in sentences.  Is this difference in f's case intended?  If not I'm happy to send up a patch with uniform `Lo-Fi` or `Lo-fi`.

**Comment by karlstolley** [comment]
Yup. All intended -- just like you noticed, it's Lo-Fi in headings/title, Lo-fi when it starts a sentence, and lo-fi within a sentence. But if you find anything that breaks that pattern, I'd be happy to have a patch.

**Comment by jsirois** [comment]
SGTM!

Also - Hey from Katie Ryan!  She pointed me at your piece - very cool stuff!
